# Chapter 26

## Imports

In [1]:
import pandas as pd
import numpy as np

## Read In Data

In [2]:
# url = "https://github.com/mattharrison/datasets/raw/master/data/2020-jetbrains-python-survey.csv"
# jb = pd.read_csv(url)

C:\Users\tmadsen\AppData\Local\Temp\ipykernel_8624\3853255871.py:2: DtypeWarning: Columns (152) have mixed types. Specify dtype option on import or set low_memory=False.
  jb = pd.read_csv(url)


In [4]:
# jb.to_parquet('data/jet_brains_python_2020_survey_data.parquet', index=False)

## 26.1 Dummy Columns

In [5]:
jb.filter(like='job.role')

job.role.DBA job.role.Architect job.role.QA engineer  \
0              NaN                NaN                  NaN   
1              NaN                NaN                  NaN   
2              NaN                NaN                  NaN   
3              NaN                NaN                  NaN   
4              NaN                NaN                  NaN   
...            ...                ...                  ...   
54457          NaN                NaN                  NaN   
54458          NaN                NaN                  NaN   
54459          NaN                NaN                  NaN   
54460          NaN                NaN                  NaN   
54461          NaN          Architect                  NaN   

      job.role.Developer / Programmer job.role.Technical writer  \
0                                 NaN                       NaN   
1              Developer / Programmer                       NaN   
2              Developer / Programmer                       NaN   
3                                 NaN                       NaN   
4                                 NaN                       NaN   
...                               ...                       ...   
54457                             NaN                       NaN   
54458                             NaN                       NaN   
54459                             NaN                       NaN   
54460          Developer / Programmer                       NaN   
54461          Developer / Programmer                       NaN   

      job.role.Technical support job.role.Data analyst  \
0                            NaN                   NaN   
1                            NaN                   NaN   
2              Technical support          Data analyst   
3                            NaN                   NaN   
4                            NaN                   NaN   
...                          ...                   ...   
54457                        NaN                   NaN   
54458                        NaN                   NaN   
54459                        NaN                   NaN   
54460                        NaN          Data analyst   
54461                        NaN                   NaN   

      job.role.Business analyst job.role.Team lead job.role.Product manager  \
0              Business analyst                NaN                      NaN   
1                           NaN                NaN                      NaN   
2                           NaN          Team lead                      NaN   
3                           NaN                NaN                      NaN   
4                           NaN                NaN                      NaN   
...                         ...                ...                      ...   
54457                       NaN                NaN                      NaN   
54458                       NaN                NaN                      NaN   
54459                       NaN                NaN                      NaN   
54460                       NaN                NaN                      NaN   
54461                       NaN          Team lead                      NaN   

      job.role.CIO / CEO / CTO job.role.Systems analyst job.role.Other  
0                          NaN                      NaN            NaN  
1                          NaN                      NaN            NaN  
2                          NaN                      NaN            NaN  
3                          NaN                      NaN            NaN  
4                          NaN                      NaN            NaN  
...                        ...                      ...            ...  
54457                      NaN          Systems analyst            NaN  
54458                      NaN                      NaN            NaN  
54459          CIO / CEO / CTO                      NaN            NaN  
54460                      NaN                      NaN            NaN  
54461  

In [8]:
jb['job.role.DBA'].unique()

array([nan, 'DBA'], dtype=object)

In [22]:
job = (jb
    .filter(like='job.role')
    .where(jb.isna(), 1)
    .fillna(0)
    .idxmax(axis='columns')
    .str.replace('job.role.', '', regex=False)
)

In [24]:
dum = pd.get_dummies(job)
dum

Architect  Business analyst  CIO / CEO / CTO  DBA  Data analyst  \
0              0                 1                0    0             0   
1              0                 0                0    0             0   
2              0                 0                0    0             0   
3              0                 0                0    1             0   
4              0                 0                0    1             0   
...          ...               ...              ...  ...           ...   
54457          0                 0                0    0             0   
54458          0                 0                0    1             0   
54459          0                 0                1    0             0   
54460          0                 0                0    0             0   
54461          1                 0                0    0             0   

       Developer / Programmer  Other  Product manager  QA engineer  \
0                           0      0                0            0   
1                           1      0                0            0   
2                           1      0                0            0   
3                           0      0                0            0   
4                           0      0                0            0   
...                       ...    ...              ...          ...   
54457                       0      0                0            0   
54458                       0      0                0            0   
54459                       0      0                0            0   
54460                       1      0                0            0   
54461                       0      0                0            0   

       Systems analyst  Team lead  Technical support  Technical writer  
0                    0          0                  0                 0  
1                    0          0                  0                 0  
2                    0          0                  0                 0  
3                    0          0                  0                 0  
4                    0          0                  0                 0  
...                ...        ...                ...               ...  
54457                1          0                  0                 0  
54458                0          0                  0                 0  
54459                0          0                  0                 0  
54460                0          0                  0                 0  
54461                0          0                  0                 0  

[54462 rows x 13 columns]

In [32]:
dum.sum()

Architect                  3118
Business analyst            135
CIO / CEO / CTO             370
DBA                       36303
Data analyst                867
Developer / Programmer     9934
Other                      1639
Product manager             129
QA engineer                 672
Systems analyst             126
Team lead                   659
Technical support           398
Technical writer            112
dtype: int64

## 26.2 Undoing Dummy Columns

In [25]:
dum.idxmax(axis='columns')

0              Business analyst
1        Developer / Programmer
2        Developer / Programmer
3                           DBA
4                           DBA
                  ...          
54457           Systems analyst
54458                       DBA
54459           CIO / CEO / CTO
54460    Developer / Programmer
54461                 Architect
Length: 54462, dtype: object

In [35]:
dum.to_numpy().shape

(54462, 13)

In [26]:
i, j = np.where(dum)

In [27]:
i

array([    0,     1,     2, ..., 54459, 54460, 54461], dtype=int64)

In [28]:
j

array([1, 5, 5, ..., 2, 5, 0], dtype=int64)

In [33]:
pd.Series(dum.columns[j], i)

0              Business analyst
1        Developer / Programmer
2        Developer / Programmer
3                           DBA
4                           DBA
                  ...          
54457           Systems analyst
54458                       DBA
54459           CIO / CEO / CTO
54460    Developer / Programmer
54461                 Architect
Length: 54462, dtype: object